spark.driver.extraJavaOptions=-Djava.security.manager=allow --add-opens=java.base/javax.security.auth=ALL-UNNAMED
spark.executor.extraJavaOptions=-Djava.security.manager=allow --add-opens=java.base/javax.security.auth=ALL-UNNAMED
